// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nigarynafypdfqnmjbiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pZ2FyeW5hZnlwZGZxbm1qYml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTY0NDMsImV4cCI6MjA2MTc3MjQ0M30.Jhn6i04ap_PRSZDqlp96dSXvkzb5u2GKpYa6tk02TEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);